---
framework: mocha
tier: small
blocklist:
  - "test/options.spec.ts##options##cwd##"
  - "./test/options.spec.ts##options##output##should work"

postMerge:
  pattern: 
    - "./test/**/*.spec.ts""
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version

parallelism : 2
version: 1.0.2
