---
framework: mocha
tier: small
blocklist:
  - "test/options.spec.ts##options##cwd##"
  - "./test/options.spec.ts##options##output##should work"
  - "./test/target.spec.ts##Targets##should stringify and toString"
  - "./test/dummy.spec.ts##dummy"
  - "./test/new_test_suite.spec.ts##new suite 1##new-test-2##"
postMerge:
  pattern: 
    - "./test/**/*.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
version: 1.13
parallelism : 2

